defualts: &defaults
  working_directory: ~/sense-api
  docker:
    - image: circleci/ruby:2.3-node-browsers
  docker:
    - image: circleci/mongo:3.4.10
  docker:
    - image: circleci/mysql:5.6
  environment: cp config/circleci/my.cnf /etc/mysql/my.cnf

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 
          command: apt-get install awscli

